# Generated by Django 4.2.5 on 2024-04-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_subject',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='group_subject',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='group_user',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='group_user',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
