# Generated by Django 4.2.5 on 2024-04-15 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_group_id_group_subject_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.role', verbose_name='Роль'),
        ),
    ]
