# Generated by Django 4.2.5 on 2024-04-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_professor_role_alter_student_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_user',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group_user',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'преподавателя', 'verbose_name_plural': 'Информация о преподавателях'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'студента', 'verbose_name_plural': 'Информация о студентах'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Дисциплину', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.student', verbose_name='ID студента'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='ID предмета'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.professor', verbose_name='ID преподавателя'),
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.IntegerField(default=1, verbose_name='Курс'),
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.DeleteModel(
            name='Group_subject',
        ),
        migrations.DeleteModel(
            name='Group_user',
        ),
    ]
