# Generated by Django 4.2.5 on 2024-05-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_group_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
