# Generated by Django 4.2.5 on 2024-05-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_professor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Балл'),
        ),
    ]
