# Generated by Django 4.2.5 on 2024-05-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_score_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='type',
            field=models.CharField(blank=True, choices=[('Тест', 'Тест'), ('Экзамен', 'Экзамен'), ('Зачет', 'Зачет'), ('Курсовая работа', 'Курсовая работа'), ('Лабораторная работа', 'Лабораторная работа'), ('Посещаемость', 'Посещаемость')], verbose_name='Тип оценивания'),
        ),
    ]
