# Generated by Django 4.2.5 on 2024-05-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_score_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('студент', 'студент'), ('преподаватель', 'преподаватель'), ('администратор', 'администратор')], verbose_name='Роль'),
        ),
    ]
