# Generated by Django 4.2.5 on 2024-05-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_group_group_name_alter_professor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default=2, max_length=20, verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student', verbose_name='ID студента'),
        ),
        migrations.AlterField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='ID предмета'),
        ),
        migrations.AlterField(
            model_name='score',
            name='type',
            field=models.CharField(blank=True, choices=[('Тест', 'Тест'), ('Экзамен', 'Экзамен'), ('Зачет', 'Зачет'), ('Курсовая работа', 'Курсовая работа'), ('Лабораторная работа', 'Лабораторная работа'), ('Посещаемость', 'Посещаемость')], verbose_name='Тип оценивания'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.IntegerField(default=1, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=100, verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.professor', verbose_name='ID преподавателя'),
        ),
    ]
